[en]
  languageName = "English"
  weight = 1
  title = "Code Plato"
  contentDir = "content/en"

  [en.params.sidebar]
    subtitle = "I believe human creativity is the real tree of AI Coding — code and models are but shadows on the cave wall."

[[en.menus.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/CodePlato3721"
  weight = 1
  params = {icon = "brand-github", newTab = true}

[[en.menus.social]]
  identifier = "x"
  name = "X"
  url = "https://x.com/codeplato2026"
  weight = 2
  params = {icon = "brand-twitter", newTab = true}

[[en.menus.social]]
  identifier = "rss"
  name = "RSS"
  url = "/index.xml"
  weight = 3
  params = {icon = "rss"}

[zh]
  languageName = "简体中文"
  weight = 2
  title = "Code Plato"
  contentDir = "content/zh"

  [zh.params.sidebar]
    subtitle = "我相信，人类的创造力才是 AI Coding 的真实之树，而代码与模型不过是投射在洞穴墙上的影子。"

[[zh.menus.social]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/CodePlato3721"
  weight = 1
  params = {icon = "brand-github", newTab = true}

[[zh.menus.social]]
  identifier = "weibo"
  name = "微博"
  url = "https://www.weibo.com/u/1041257881"
  weight = 2
  params = {icon = "brand-weibo", newTab = true}

[[zh.menus.social]]
  identifier = "rss"
  name = "RSS"
  url = "/zh/index.xml"
  weight = 3
  params = {icon = "rss"}
